/*-
 * Copyright (C) 2011 Erik Larsson
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.catacombae.hfs.types.hfsplus;

import java.io.PrintStream;
import org.catacombae.csjc.PrintableStruct;
import org.catacombae.csjc.StaticStruct;
import org.catacombae.util.Util;

/** This class was generated by CStructToJavaClass. */
public class HFSPlusAttrForkData implements StaticStruct, PrintableStruct {
    /*
     * struct HFSPlusAttrForkData
     * size: 88 bytes
     * description:
     *
     * BP  Size  Type             Identifier  Description
     * --------------------------------------------------
     * 0   4     UInt32           recordType
     * 4   4     UInt32           reserved
     * 8   80    HFSPlusForkData  theFork
     */

    public static final int STRUCTSIZE = 88;

    private int recordType;
    private int reserved;
    private final HFSPlusForkData theFork;

    public HFSPlusAttrForkData(byte[] data, int offset) {
        recordType = Util.readIntBE(data, offset+0);
        reserved = Util.readIntBE(data, offset+4);
        theFork = new HFSPlusForkData(data, offset+8);
    }

    public static int length() { return STRUCTSIZE; }

    public int size() { return length(); }

    /**  */
    public final long getRecordType() { return Util.unsign(getRawRecordType()); }
    /**  */
    public final long getReserved() { return Util.unsign(getRawReserved()); }
    /**  */
    public final HFSPlusForkData getTheFork() { return theFork; }

    /** <b>Note that the return value from this function should be interpreted as an unsigned integer, for instance using Util.unsign(...).</b> */
    public final int getRawRecordType() { return recordType; }
    /** <b>Note that the return value from this function should be interpreted as an unsigned integer, for instance using Util.unsign(...).</b> */
    public final int getRawReserved() { return reserved; }

    public void printFields(PrintStream ps, String prefix) {
        ps.println(prefix + " recordType: " + getRecordType());
        ps.println(prefix + " reserved: " + getReserved());
        ps.println(prefix + " theFork: ");
        getTheFork().print(ps, prefix + "  ");
    }

    public void print(PrintStream ps, String prefix) {
        ps.println(prefix + "HFSPlusAttrForkData:");
        printFields(ps, prefix);
    }

    public byte[] getBytes() {
        byte[] result = new byte[length()];
        int offset = 0;

        Util.arrayPutBE(result, offset, recordType); offset += 4;
        Util.arrayPutBE(result, offset, reserved); offset += 4;
        {
            byte[] tempData = this.theFork.getBytes();
            System.arraycopy(tempData, 0, result, offset, tempData.length); offset += tempData.length;
        }

        return result;
    }
}
