import java.io.PrintStream;

/** This class was generated by CStructToJavaClass. */
public class Rect {
    /*
     * struct Rect
     * size: 8 bytes
     * description: 
     * 
     * BP  Size  Type    Identifier  Description
     * -----------------------------------------
     * 0   2     SInt16  top                    
     * 2   2     SInt16  left                   
     * 4   2     SInt16  bottom                 
     * 6   2     SInt16  right                  
     */
    
    private final byte[] top = new byte[2];
    private final byte[] left = new byte[2];
    private final byte[] bottom = new byte[2];
    private final byte[] right = new byte[2];
    
    public Rect(byte[] data, int offset) {
	System.arraycopy(data, offset+0, top, 0, 2);
	System.arraycopy(data, offset+2, left, 0, 2);
	System.arraycopy(data, offset+4, bottom, 0, 2);
	System.arraycopy(data, offset+6, right, 0, 2);
    }
    
    public static int length() { return 8; }
    
    public short getTop() { return Util.readShortBE(top); }
    public short getLeft() { return Util.readShortBE(left); }
    public short getBottom() { return Util.readShortBE(bottom); }
    public short getRight() { return Util.readShortBE(right); }
    
    public void printFields(PrintStream ps, String prefix) {
	ps.println(prefix + " top: " + getTop());
	ps.println(prefix + " left: " + getLeft());
	ps.println(prefix + " bottom: " + getBottom());
	ps.println(prefix + " right: " + getRight());
    }
    
    public void print(PrintStream ps, String prefix) {
	ps.println(prefix + "Rect:");
	printFields(ps, prefix);
    }
}
