/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WindowsLowLevelIO */

#ifndef _Included_WindowsLowLevelIO
#define _Included_WindowsLowLevelIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WindowsLowLevelIO
 * Method:    open
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_WindowsLowLevelIO_open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     WindowsLowLevelIO
 * Method:    seek
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_WindowsLowLevelIO_seek
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     WindowsLowLevelIO
 * Method:    read
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_WindowsLowLevelIO_read
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     WindowsLowLevelIO
 * Method:    close
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_WindowsLowLevelIO_close
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     WindowsLowLevelIO
 * Method:    ejectMedia
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_WindowsLowLevelIO_ejectMedia
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     WindowsLowLevelIO
 * Method:    loadMedia
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_WindowsLowLevelIO_loadMedia
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
