/*-
 * Copyright (C) 2006 Erik Larsson
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.catacombae.hfsexplorer.types;

import org.catacombae.hfsexplorer.Util;
import org.catacombae.hfsexplorer.Util2;
import java.io.PrintStream;

/** This class was generated by CStructToJavaClass. */
public class Point {
    /*
     * struct Point
     * size: 4 bytes
     * description: 
     * 
     * BP  Size  Type    Identifier  Description
     * -----------------------------------------
     * 0   2     SInt16  v                      
     * 2   2     SInt16  h                      
     */
    
    private final byte[] v = new byte[2];
    private final byte[] h = new byte[2];
    
    public Point(byte[] data, int offset) {
	System.arraycopy(data, offset+0, v, 0, 2);
	System.arraycopy(data, offset+2, h, 0, 2);
    }
    
    public static int length() { return 4; }
    
    public short getV() { return Util.readShortBE(v); }
    public short getH() { return Util.readShortBE(h); }

    public String toString() { return "(" + getV() + "," + getH() + ")"; }
    
    public void printFields(PrintStream ps, String prefix) {
	ps.println(prefix + " v: " + getV());
	ps.println(prefix + " h: " + getH());
    }
    
    public void print(PrintStream ps, String prefix) {
	ps.println(prefix + "Point:");
	printFields(ps, prefix);
    }
}
