/*
 * DateSummaryPanel.java
 *
 * Created on den 31 oktober 2008, 18:37
 */

package org.catacombae.hfsexplorer.gui;

import java.awt.Component;
import java.text.DateFormat;
import org.catacombae.jparted.lib.fs.FSAttributes;

/**
 *
 * @author  Erik
 */
public class DateSummaryPanel extends javax.swing.JPanel implements ChainedPanel {

    /** Creates new form DateSummaryPanel */
    public DateSummaryPanel(FSAttributes attributes) {
        initComponents();
        
        DateFormat df = DateFormat.getDateTimeInstance(DateFormat.SHORT, DateFormat.MEDIUM);
        if(attributes.hasCreateDate())
            createField.setText(df.format(attributes.getCreateDate()));
        else {
            //createLabel.setVisible(false);
            createField.setText("<not available>");
        }
            
        if(attributes.hasModifyDate())
            contentModField.setText(df.format(attributes.getModifyDate()));
        else {
            //contentModLabel.setVisible(false);
            contentModField.setText("<not available>");
        }
            
        if(attributes.hasAttributeModifyDate())
            attributeModField.setText(df.format(attributes.getAttributeModifyDate()));
        else {
            //attributeModLabel.setVisible(false);
            attributeModField.setText("<not available>");
        }
            
        if(attributes.hasAccessDate())
            accessField.setText(df.format(attributes.getAccessDate()));
        else {
            //accessLabel.setVisible(false);
            accessField.setText("<not available>");
        }
            
        if(attributes.hasBackupDate())
            backupField.setText(df.format(attributes.getBackupDate()));
        else {
            //backupLabel.setVisible(false);
            backupField.setText("<not available>");
        }
                    
        //if(attributes.hasDate())
        //    createField.setText(attributes.getDate().toString());
    }
    
    @Override
    public void setChainedContents(Component c) {
        chainedContentsPanel.removeAll();
        chainedContentsPanel.add(c);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createLabel = new javax.swing.JLabel();
        contentModLabel = new javax.swing.JLabel();
        attributeModLabel = new javax.swing.JLabel();
        accessLabel = new javax.swing.JLabel();
        backupLabel = new javax.swing.JLabel();
        createField = new javax.swing.JTextField();
        contentModField = new javax.swing.JTextField();
        attributeModField = new javax.swing.JTextField();
        accessField = new javax.swing.JTextField();
        backupField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        chainedContentsPanel = new javax.swing.JPanel();

        createLabel.setText("Created:");

        contentModLabel.setText("Contents modified:");

        attributeModLabel.setText("Attributes modified:");

        accessLabel.setText("Last accessed:");

        backupLabel.setText("Last backuped:");

        createField.setEditable(false);
        createField.setText("jTextField1");
        createField.setBorder(null);
        createField.setOpaque(false);

        contentModField.setEditable(false);
        contentModField.setText("jTextField2");
        contentModField.setBorder(null);
        contentModField.setOpaque(false);

        attributeModField.setEditable(false);
        attributeModField.setText("jTextField5");
        attributeModField.setBorder(null);
        attributeModField.setOpaque(false);

        accessField.setEditable(false);
        accessField.setText("jTextField3");
        accessField.setBorder(null);
        accessField.setOpaque(false);

        backupField.setEditable(false);
        backupField.setText("jTextField4");
        backupField.setBorder(null);
        backupField.setOpaque(false);

        chainedContentsPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(attributeModLabel)
                    .addComponent(contentModLabel)
                    .addComponent(accessLabel)
                    .addComponent(backupLabel)
                    .addComponent(createLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createField, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(backupField, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(accessField, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(contentModField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(attributeModField, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
            .addComponent(chainedContentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createLabel)
                    .addComponent(createField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contentModLabel)
                    .addComponent(contentModField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attributeModLabel)
                    .addComponent(attributeModField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accessLabel)
                    .addComponent(accessField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backupLabel)
                    .addComponent(backupField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chainedContentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accessField;
    private javax.swing.JLabel accessLabel;
    private javax.swing.JTextField attributeModField;
    private javax.swing.JLabel attributeModLabel;
    private javax.swing.JTextField backupField;
    private javax.swing.JLabel backupLabel;
    private javax.swing.JPanel chainedContentsPanel;
    private javax.swing.JTextField contentModField;
    private javax.swing.JLabel contentModLabel;
    private javax.swing.JTextField createField;
    private javax.swing.JLabel createLabel;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
