/*
 * ErrorSummaryPanel.java
 *
 * Created on den 31 oktober 2008, 17:19
 */

package org.catacombae.hfsexplorer.gui;

import java.awt.Dialog.ModalityType;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JDialog;

/**
 *
 * @author  Erik
 */
public class ErrorSummaryPanel extends javax.swing.JPanel {

    private ErrorSummaryPanel(final JDialog dialog, List<String> errorMessages) {
        this(errorMessages);
        
        closeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dialog.dispose();
            }
        });
        
        
    }
    /** Creates new form ErrorSummaryPanel */
    private ErrorSummaryPanel(List<String> errorMessages) {
        initComponents();
        
        for(String msg : errorMessages) {
            contentsAreaScroller.append(msg + "\n");
        }
    }
    
    public static JDialog createErrorSummaryDialog(Window owner, List<String> errorMessages) {
        JDialog dialog = new JDialog(owner, "Error summary", ModalityType.DOCUMENT_MODAL);
        ErrorSummaryPanel esp = new ErrorSummaryPanel(dialog, errorMessages);
        dialog.add(esp);
        
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        
        return dialog;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        contantsAreaScroller = new javax.swing.JScrollPane();
        contentsAreaScroller = new javax.swing.JTextArea();
        closeButtonPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        titleLabel.setText("The following errors were encountered when extracting files:");

        contentsAreaScroller.setColumns(20);
        contentsAreaScroller.setEditable(false);
        contentsAreaScroller.setLineWrap(true);
        contentsAreaScroller.setRows(5);
        contantsAreaScroller.setViewportView(contentsAreaScroller);

        closeButtonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        closeButton.setText("Close");
        closeButtonPanel.add(closeButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contantsAreaScroller, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeButtonPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contantsAreaScroller, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel closeButtonPanel;
    private javax.swing.JScrollPane contantsAreaScroller;
    private javax.swing.JTextArea contentsAreaScroller;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

}
