/*-
 * Copyright (C) 2007 Erik Larsson
 * 
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
 */

/*
 * ExtractProgressPanel.java
 *
 * Created on den 3 april 2007, 09:02
 */

package org.catacombae.hfsexplorer.gui;
import org.catacombae.hfsexplorer.*;
import javax.swing.SwingUtilities;
import java.text.DecimalFormat;

/**
 *
 * @author  Erik
 */
public class ExtractProgressPanel extends javax.swing.JPanel {
    private final DecimalFormat progressFormatter = new DecimalFormat("0.0");
    private final DecimalFormat fileSizeFormatter = new DecimalFormat("0.00");
    /** Creates new form ExtractProgressPanel */
    public ExtractProgressPanel() {
        initComponents();
        progressBar.setMinimum(0);
        progressBar.setMaximum(Integer.MAX_VALUE);
    }
    
    /** <code>fraction</code> must be between 0 and 1. */
    public void updateTotalProgress(final double fraction, final String message) {
	// just to be sure no deadlocks arise...
	SwingUtilities.invokeLater(new Runnable() {
		public void run() {
		    progressBar.setValue((int)(fraction*Integer.MAX_VALUE));
		    progressBar.setString((progressFormatter.format(100*fraction) + "% (" + message + ")"));
		}});
    }
    
    public void updateCurrentDir(final String dirname) {
	SwingUtilities.invokeLater(new Runnable() {
		public void run() {
		    currentFilenameLabel.setText("Extracting: " + dirname);
		}});
    }

    public void updateCurrentFile(final String filename, final long fileSize) {
	SwingUtilities.invokeLater(new Runnable() {
		public void run() {
		    currentFilenameLabel.setText("Extracting: " + filename +  " (" + SpeedUnitUtils.bytesToBinaryUnit(fileSize, fileSizeFormatter) + ")");
		}});
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        progressBar = new javax.swing.JProgressBar();
        cancelButton = new javax.swing.JButton();
        currentFilenameLabel = new javax.swing.JLabel();

        progressBar.setString("Calculating...");
        progressBar.setStringPainted(true);

        cancelButton.setText("Cancel");

        currentFilenameLabel.setText("Calculating selection size...");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(currentFilenameLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(progressBar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(currentFilenameLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(progressBar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .add(cancelButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cancelButton;
    private javax.swing.JLabel currentFilenameLabel;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
    
}
