/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FlagViewPanel.java
 *
 * Created on 2008-sep-30, 09:54:16
 */

package org.catacombae.hfsexplorer.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import org.catacombae.csjc.structelements.FlagField;

/**
 *
 * @author erik
 */
public class FlagViewPanel extends javax.swing.JPanel {

    /** Creates new form FlagViewPanel */
    public FlagViewPanel(String label, final FlagField data) {
        initComponents();
        
        if(false) {
            flagBox.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    flagBox.setSelected(data.getValueAsBoolean());
                }
            });
        }
        else
            flagBox.setEnabled(false);
        
        flagBox.setSelected(data.getValueAsBoolean());
        flagLabel.setText(label);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flagBox = new javax.swing.JCheckBox();
        flagLabel = new javax.swing.JLabel();

        flagBox.setBorder(null);
        flagBox.setFocusable(false);

        flagLabel.setText("jLabel1");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(flagBox)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(flagLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(flagBox)
                .add(flagLabel))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox flagBox;
    private javax.swing.JLabel flagLabel;
    // End of variables declaration//GEN-END:variables

}
