/*
 * ContainerPanel.java
 *
 * Created on den 17 augusti 2008, 14:19
 */

package org.catacombae.hfsexplorer.testcode.editgpt;

import javax.swing.Box;
import javax.swing.JComponent;
import org.catacombae.csjc.StructElements.Dictionary;
import org.catacombae.csjc.StructElements.Field;
import org.catacombae.csjc.StructElements.StructElement;

/**
 *
 * @author  Erik
 */
public class ContainerPanel extends javax.swing.JPanel {

    public ContainerPanel() {
        this(null);
    }
    
    /** Creates new form ContainerPanel */
    public ContainerPanel(String label) {
        initComponents();
        
        if(label != null)
            descriptionLabel.setText(label);
        else
            descriptionLabel.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentsPanel = new javax.swing.JPanel();
        descriptionLabel = new javax.swing.JLabel();

        contentsPanel.setLayout(new javax.swing.BoxLayout(contentsPanel, javax.swing.BoxLayout.PAGE_AXIS));

        descriptionLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(contentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                    .addComponent(descriptionLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setFields(Dictionary rootDict) {
        String[] keys = rootDict.getKeys();
        
        for(String key : keys) {
            System.err.println("setFields processing key \"" + key + "\"...");
            StructElement curElem = rootDict.getElement(key);
            System.err.println("  curElem = " + curElem);
            if(curElem instanceof Field) {
                Field curField = (Field)curElem;
                EditStringValuePanel panel = new EditStringValuePanel();
                panel.setDecription(key + " (" + curField.getTypeName() + ")");
                panel.setValue(curField.getValueAsString());
                System.err.println("  (1)adding " + panel + " to containerpanel");
                addComponent(panel);
            }
            else if(curElem instanceof Dictionary) {
                Dictionary curDict = (Dictionary)curElem;
                ContainerPanel panel = new ContainerPanel(key + " (" + curDict.getTypeName() + ")");
                panel.setFields(curDict);
                System.err.println("  (2)adding " + panel + " to containerpanel");
                addComponent(panel);
            }
        }
    }
    
    private void addComponent(JComponent jc) {
        contentsPanel.add(jc);
        contentsPanel.add(Box.createVerticalGlue());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentsPanel;
    private javax.swing.JLabel descriptionLabel;
    // End of variables declaration//GEN-END:variables

}
