/*
 * EditStringValuePanel.java
 *
 * Created on den 17 augusti 2008, 14:00
 */

package org.catacombae.hfsexplorer.testcode.editgpt;

/**
 *
 * @author  Erik
 */
public class EditStringValuePanel extends javax.swing.JPanel {

    /** Creates new form EditStringValuePanel */
    public EditStringValuePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentsField = new javax.swing.JTextField();
        lockedCheckbox = new javax.swing.JCheckBox();
        descriptionLabel = new javax.swing.JLabel();

        contentsField.setEditable(false);
        contentsField.setText("jTextField1");

        lockedCheckbox.setSelected(true);
        lockedCheckbox.setText("Locked");
        lockedCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lockedCheckboxActionPerformed(evt);
            }
        });

        descriptionLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(descriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentsField, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lockedCheckbox))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(descriptionLabel)
                .addComponent(contentsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lockedCheckbox))
        );
    }// </editor-fold>//GEN-END:initComponents

private void lockedCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lockedCheckboxActionPerformed
    if(lockedCheckbox.isSelected())
        contentsField.setEditable(false);
    else
        contentsField.setEditable(true);
}//GEN-LAST:event_lockedCheckboxActionPerformed

    public void setDecription(String s) {
        descriptionLabel.setText(s);
    }
    
    public void setValue(String value) {
        contentsField.setText(value);
    }
    
    public String getValue() {
        return contentsField.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contentsField;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JCheckBox lockedCheckbox;
    // End of variables declaration//GEN-END:variables

}
