/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_catacombae_hfsexplorer_win32_WindowsLowLevelIO */

#ifndef _Included_org_catacombae_hfsexplorer_win32_WindowsLowLevelIO
#define _Included_org_catacombae_hfsexplorer_win32_WindowsLowLevelIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_catacombae_hfsexplorer_win32_WindowsLowLevelIO
 * Method:    openNative
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_catacombae_hfsexplorer_win32_WindowsLowLevelIO_openNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_catacombae_hfsexplorer_win32_WindowsLowLevelIO
 * Method:    seek
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_catacombae_hfsexplorer_win32_WindowsLowLevelIO_seek
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_catacombae_hfsexplorer_win32_WindowsLowLevelIO
 * Method:    read
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_org_catacombae_hfsexplorer_win32_WindowsLowLevelIO_read
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     org_catacombae_hfsexplorer_win32_WindowsLowLevelIO
 * Method:    close
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_org_catacombae_hfsexplorer_win32_WindowsLowLevelIO_close
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_catacombae_hfsexplorer_win32_WindowsLowLevelIO
 * Method:    ejectMedia
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_org_catacombae_hfsexplorer_win32_WindowsLowLevelIO_ejectMedia
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_catacombae_hfsexplorer_win32_WindowsLowLevelIO
 * Method:    loadMedia
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_org_catacombae_hfsexplorer_win32_WindowsLowLevelIO_loadMedia
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_catacombae_hfsexplorer_win32_WindowsLowLevelIO
 * Method:    length
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_catacombae_hfsexplorer_win32_WindowsLowLevelIO_length
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_catacombae_hfsexplorer_win32_WindowsLowLevelIO
 * Method:    getFilePointer
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_catacombae_hfsexplorer_win32_WindowsLowLevelIO_getFilePointer
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_catacombae_hfsexplorer_win32_WindowsLowLevelIO
 * Method:    getSectorSize
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_catacombae_hfsexplorer_win32_WindowsLowLevelIO_getSectorSize
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
