import java.io.PrintStream;

/** This class was generated by CStructToJavaClass. */
public class HFSPlusBSDInfo {
    /*
     * struct HFSPlusBSDInfo
     * size: 16 bytes
     * description: 
     * 
     * BP  Size  Type    Identifier  Description
     * -----------------------------------------
     * 0   4     UInt32  ownerID                
     * 4   4     UInt32  groupID                
     * 8   1     UInt8   adminFlags             
     * 9   1     UInt8   ownerFlags             
     * 10  2     UInt16  fileMode               
     * 12  4     UInt32  special                
     */
    
    private final byte[] ownerID = new byte[4];
    private final byte[] groupID = new byte[4];
    private final byte[] adminFlags = new byte[1];
    private final byte[] ownerFlags = new byte[1];
    private final byte[] fileMode = new byte[2];
    private final byte[] special = new byte[4];
    
    public HFSPlusBSDInfo(byte[] data, int offset) {
	System.arraycopy(data, offset+0, ownerID, 0, 4);
	System.arraycopy(data, offset+4, groupID, 0, 4);
	System.arraycopy(data, offset+8, adminFlags, 0, 1);
	System.arraycopy(data, offset+9, ownerFlags, 0, 1);
	System.arraycopy(data, offset+10, fileMode, 0, 2);
	System.arraycopy(data, offset+12, special, 0, 4);
    }
    
    public static int length() { return 16; }
    
    public int getOwnerID() { return Util.readIntBE(ownerID); }
    public int getGroupID() { return Util.readIntBE(groupID); }
    public byte getAdminFlags() { return Util.readByteBE(adminFlags); }
    public byte getOwnerFlags() { return Util.readByteBE(ownerFlags); }
    public short getFileMode() { return Util.readShortBE(fileMode); }
    public int getSpecial() { return Util.readIntBE(special); }
    
    public void printFields(PrintStream ps, String prefix) {
	ps.println(prefix + " ownerID: " + getOwnerID());
	ps.println(prefix + " groupID: " + getGroupID());
	ps.println(prefix + " adminFlags: " + getAdminFlags());
	ps.println(prefix + " ownerFlags: " + getOwnerFlags());
	ps.println(prefix + " fileMode: " + getFileMode());
	ps.println(prefix + " special: " + getSpecial());
    }
    
    public void print(PrintStream ps, String prefix) {
	ps.println(prefix + "HFSPlusBSDInfo:");
	printFields(ps, prefix);
    }
}
