package org.catacombae.hfsexplorer.types.hfs;

import java.io.PrintStream;
import org.catacombae.hfsexplorer.Util;

/** This class was generated by CStructToJavaClass. */
public class ExtKeyRec {
    /*
     * struct ExtKeyRec
     * size: 8 bytes
     * description: 
     * 
     * BP  Size  Type    Identifier  Description                             
     * ----------------------------------------------------------------------
     * 0   1     SInt8   xkrKeyLen   key length (SignedByte)                 
     * 1   1     SInt8   xkrFkType   fork type (SignedByte)                  
     * 2   4     SInt32  xkrFNum     file number (LongInt)                   
     * 6   2     SInt16  xkrFABN     starting file allocation block (Integer)
     */
    
    public static final int STRUCTSIZE = 8;
    
    private final byte[] xkrKeyLen = new byte[1];
    private final byte[] xkrFkType = new byte[1];
    private final byte[] xkrFNum = new byte[4];
    private final byte[] xkrFABN = new byte[2];
    
    public ExtKeyRec(byte[] data, int offset) {
	System.arraycopy(data, offset+0, xkrKeyLen, 0, 1);
	System.arraycopy(data, offset+1, xkrFkType, 0, 1);
	System.arraycopy(data, offset+2, xkrFNum, 0, 4);
	System.arraycopy(data, offset+6, xkrFABN, 0, 2);
    }
    
    public static int length() { return STRUCTSIZE; }
    
    /** key length (SignedByte) */
    public byte getXkrKeyLen() { return Util.readByteBE(xkrKeyLen); }
    /** fork type (SignedByte) */
    public byte getXkrFkType() { return Util.readByteBE(xkrFkType); }
    /** file number (LongInt) */
    public int getXkrFNum() { return Util.readIntBE(xkrFNum); }
    /** starting file allocation block (Integer) */
    public short getXkrFABN() { return Util.readShortBE(xkrFABN); }
    
    public void printFields(PrintStream ps, String prefix) {
	ps.println(prefix + " xkrKeyLen: " + getXkrKeyLen());
	ps.println(prefix + " xkrFkType: " + getXkrFkType());
	ps.println(prefix + " xkrFNum: " + getXkrFNum());
	ps.println(prefix + " xkrFABN: " + getXkrFABN());
    }
    
    public void print(PrintStream ps, String prefix) {
	ps.println(prefix + "ExtKeyRec:");
	printFields(ps, prefix);
    }
    
    public byte[] getBytes() {
	byte[] result = new byte[STRUCTSIZE];
	int offset = 0;
	System.arraycopy(xkrKeyLen, 0, result, offset, xkrKeyLen.length); offset += xkrKeyLen.length;
	System.arraycopy(xkrFkType, 0, result, offset, xkrFkType.length); offset += xkrFkType.length;
	System.arraycopy(xkrFNum, 0, result, offset, xkrFNum.length); offset += xkrFNum.length;
	System.arraycopy(xkrFABN, 0, result, offset, xkrFABN.length); offset += xkrFABN.length;
	return result;
    }
}
